name: Trigger auto deployment for uptimekuma

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/uptimekuma-AutoDeployTrigger-d88a94ea-6fd4-4f16-9699-f1febf5bece6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.UPTIMEKUMA_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.UPTIMEKUMA_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.UPTIMEKUMA_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: 
          registryUsername: ${{ secrets.UPTIMEKUMA_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.UPTIMEKUMA_REGISTRY_PASSWORD }}
          containerAppName: uptimekuma
          resourceGroup: sr-app-dev-mon-rg-01
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


